### ISSUE TITLE
Security of the SimpleAggregator backend?

### ISSUE THREAD

**Issue by til** [kennethjiang/Teleport-NSLog#10]
I'm not familiar with Go, so please excuse me if I'm wrong, but wouldn't it be possible to pass in a string like e.g. "../../../home/deployer/.ssh/authorized_keys" for the `devid` parameter and make it append the posted data to any file on the server that the backend process has the rights to write? Or does Go apply some filtering of the URL parameters that prevents that?

https://github.com/kennethjiang/Teleport-NSLog/blob/master/SimpleAggregator/aggregator.go#L43

**Comment by kennethjiang** [comment]
I don't think Go has built-in mechanism to prevent attacks like this.

SimpleAggregator is a simplistic aggregator implementation (and hence the name!) that shouldn't be used in production. Feel free to implement a more sophisticated one and I will merge your pull request.

Having said that, there are a few preventative measures you can take if you want to put this SimpleAggregator to some serious use:
- run it under a user that  has read/write permission to only "logs" directory.
- Set home directory of that user to /dev/null.

PS. I have been running a SimpleAggregator on an AWS VM for a few years without any problems. Although, again, it is NOT recommended for production.

**Comment by til** [comment]
Thanks for the clarification. I was pointed to this by a colleague asking to install it on one of our servers, apparently there was a misunderstanding about the production readyness of SimpleAggregator, sorry about that. A note in the README like the one suggested in the PR might help.
