### ISSUE TITLE
nslog timestamp

### ISSUE THREAD

**Issue by edoardoc** [kennethjiang/Teleport-NSLog#12]
Hello,

this is not really an issue with nslogger, which works very well as a forwarder.
I need some help trying to understand how can I configure the timezone of nslog timestamp, right now it seems it shows times and dates in the device timezone.
Is there a way to have it in a unified timezone? such as UTC or anything else...

thanks

**Comment by kennethjiang** [comment]
Unfortunately I have never figured this out myself. :( It's quite annoying that NSLog doesn't provide this flexibility...

**Comment by edoardoc** [comment]
don't have time now but I will work something out :)

thanks again for the teleport, works really well

**Comment by edoardoc** [comment]
ok, found a way, just redefine NSLog with 

`
#ifdef __OBJC__
#define __FILE_NAME_ONLY__ [[[NSString stringWithUTF8String:__FILE__] lastPathComponent] UTF8String]
#else
#define __FILE_NAME_ONLY__ ""
#endif
#define NSLog(...) printf("[%f_%-30s:%4d]: %s\n", [[NSDate date]timeIntervalSince1970], __FILE_NAME_ONLY__, __LINE__, [[NSString stringWithFormat:__VA_ARGS__] UTF8String])

`

**Comment by kennethjiang** [comment]
🏆
